version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./numba-cache:/tmp/numba_cache
    env_file:
      - .env
    environment:
      - MODEL_NAME=./models/emotion
    depends_on:
      - mongo
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mongo-data:
